[customizations.installer]
# false = установка интерактивная через Anaconda
unattended = false

#[[customizations.user]]
#name = "user"
# пароль SHA-512
#password = "rooftop"
#groups = ["wheel"]
#description = "Mix Engineer"

[customizations.installer.modules]
enable = [
"org.fedoraproject.Anaconda.Modules.Network" ,
"org.fedoraproject.Anaconda.Modules.Payloads" ,
"org.fedoraproject.Anaconda.Modules.Security" ,
"org.fedoraproject.Anaconda.Modules.Services" ,
"org.fedoraproject.Anaconda.Modules.Storage" ,
"org.fedoraproject.Anaconda.Modules.Users" ,
]

#[customizations.iso]
#volume_id = "RAOS"
#application_id = "Test image"
#publisher = "Rooftop Studio"

[customizations.installer.kickstart]
contents = """
interactive
bootloader --location=none
"""
