[customizations.installer]
# false = установка интерактивная через Anaconda
unattended = false

[[customizations.user]]
name = "mixengineer"
# пароль SHA-512
password = "$6$rounds=4096$salt$LpUvJm9zU8X6pGvF6H8f9K/4/m8jO/vUvS1yGvQ1"
groups = ["wheel"]
description = "Mix Engineer"

[customizations.network]
hostname = "rooftop-atomic"
