[customizations.installer]
# false = установка интерактивная через Anaconda
unattended = false

[[customizations.user]]
name = "user"
# пароль SHA-512
password = "rooftop"
groups = ["wheel"]
description = "Mix Engineer"
