[customizations.installer]
unattended = false

[customizations.bootloader]
variant = "systemd-boot"

[[customizations.installer.disks]]
name = "atomicOS"

[[customizations.installer.disks.partitions]]
mountpoint = "/boot"
fs-type = "vfat"
size = "2G"

[[customizations.installer.disks.partitions]]
mountpoint = "/"
fs-type = "ext4"
size = "100%"

#[[customizations.user]]
#name = "mixengineer"
#password = "$6$rounds=4096$salt$LpUvJm9zU8X6pGvF6H8f9K/4/m8jO/vUvS1yGvQ1"
#groups = ["wheel"]
#description = "Mix Engineer"

[customizations.network]
hostname = "rooftop-atomic"
