name: Build Rooftop ISO
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO using bootc-image-builder
        uses: osbuild/bootc-image-builder-action@main
        with:
          # Указываем контекст сборки (текущая папка)
          # Это заставит его увидеть твой Containerfile
          image: localhost/rooftop-atomic:latest
          config-file: config.toml
          types: iso
