name: Build Rooftop ISO
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Container Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: rooftop-atomic
          tags: latest
          containerfiles: ./Containerfile

      - name: Verify config.toml
        run: ls -l ./config.toml

      - name: Build ISO using bootc-image-builder
        uses: osbuild/bootc-image-builder-action@main
        with:
          image: rooftop-atomic:latest
          config-file: ./config.toml
          types: iso
